### ISSUE TITLE
v-item conflict

### ISSUE THREAD

**Issue by ToxicTree** [Viva-Resurs/ReturButikenOnline#14]
Since we use two tables, one for mobile and one for desktop, the directive v-item get problems when triggering "removed".

Steps:
Component method: Remove
API remove
Success: $table.trigger 'removed'   (there are two listeners now)
Directive: Transition   (two transitions, one not visible)
Callback: transition onComplete: Vue.set removed

Visible results: First table in DOM order make the transition and keep the item while the second does nothing

(API works as normal)

Solutions:
Use Vue to choose layout?
Check transition and only run the visible element?

**Comment by notzep** [comment]
Fixed (f007319) by using a new ScreenSize mixin. Only one table is now present in DOM when selecting a desktop or mobile layout.
